services:
  chat:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    ports:
      - "443:8888"
      - "80:80"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    restart: always
    platform: linux/amd64
    environment:
      - CCACHE_DIR=/ccache
      - CCACHE_MAXSIZE=10G